language: python
python:
  - 2.7
env:
  - DOCKERINDEX_LOCAL="DATT_TRAVISCI"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
# - sudo git clone https://github.com/SimonKagstrom/shcov; cd shcov; python setup.py install
# install:
#   - pip install coveralls --use-mirrors
script:
  - make install
  - bats tests/* --tap
# after_script:
# - bash -ex coveralls.sh
# after_success:
#   - coveralls
notifications:
  email:
    on_success: never
