language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
  - DOCKERINDEX_LOCAL="DATT_TRAVISCI"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
install:
  - pip install coveralls --use-mirrors
script:
  - bats tests --tap
  - coverage report -m
after_success:
  - coveralls
notifications:
  email:
    on_success: never
